apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        ports:
        - containerPort: 8080
        env:
        - name: ADMINER_DEFAULT_SERVER
          valueFrom:
            secretKeyRef:
              name: onepay-api-secrets
              key: MYSQL_SERVER
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  selector:
    app: adminer
  ports:
    - protocol: TCP
      nodePort: 30000
      port: 8080
      targetPort: 8080
  type: NodePort
